name: doctorbranch
favicon: null
layout_spectrum: 0.7287580266129225
typography_spectrum: 0.4994071873370558
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8290672667790204
  lightness: 0.4756225331220776
  saturation: 0.1706437934190035
  rhythmicContrast: 0.2197639080695808
purpose: []
